---
openapi: 3.0.0
info:
  title: API-Catalog
  description: This is the documentation of the API to obtain all the information
    about the catalog
  version: 1.0.0
tags:
- name: Catalog
  description: Operations about the catalog
paths:
  /city:
    get:
      summary: Retrieve city resources.
      description: Retrieve a bunch of city resources. Specify example resource as body payload.
      operationId: getCity
      responses:
        200:
          description: Get an array of city resources.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CityDTO'
              examples:
                  cities:
                      value:
                      - code: "BUE"
                        name: "Buenos Aires"
                        timeZone: "America/Buenos_Aires"
                      - code: "SCL"
                        name: "Santiago de Chile"
                        timeZone: "America/Santiago"
    post:
      summary: Create new city resource.
      description: Create a new city resource. Specify payload within request body.
      requestBody:
        description: The payload of resource city to create.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CityDTO'
            examples:
                Buenos Aires:
                  value:
                    code: "BUE"
                    name: "Buenos Aires"
                    timeZone: "America/Buenos_Aires"
                Santiago de Chile:
                  value:
                    code: "SCL"
                    name: "Santiago de Chile"
                    timeZone: "America/Santiago"
      responses:
        201:
          description: Get the newly created city resource.
          content:
            application/json:
              schema:
                 $ref: '#/components/schemas/CityDTO'
              examples:
                Buenos Aires:
                  value:
                    code: "BUE"
                    name: "Buenos Aires"
                    timeZone: "America/Buenos_Aires"
                Santiago de Chile:
                  value:
                    code: "SCL"
                    name: "Santiago de Chile"
                    timeZone: "America/Santiago"
  /city/{code}:
    get:
      summary: Retrieve a city resource.
      description: Retrieve an already existing city resource having the specified id.
      operationId: getCityById
      parameters:
      - examples:
          Buenos Aires:
            value: "BUE"
          Santiago de Chile:
            value: "SCL"        
        name: code
        description: code name
        schema:
          type: string
        in: path
        required: true
      responses:
        200:
          description: city resource having specified id.
          content:
            application/json:
              schema:
                 $ref: '#/components/schemas/CityDTO'
              examples:
                Buenos Aires:
                  value:
                    code: "BUE"
                    name: "Buenos Aires"
                    timeZone: "America/Buenos_Aires"
                Santiago de Chile:
                  value:
                    code: "SCL"
                    name: "Santiago de Chile"
                    timeZone: "America/Santiago"
        404:
          description: city not exist
    put:
      summary: Update a city resource.
      description: Update an already existing city resource having the specified id.
      parameters:
      - examples:
          Buenos Aires:
            value: "BUE"
          Santiago de Chile:
            value: "SCL"        
        name: code
        description: code name
        schema:
          type: string
        in: path
        required: true
      requestBody:
        description: The payload of resource city to update.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CityDTO'
            examples:
                Buenos Aires:
                  value:
                    code: "BUE"
                    name: "Buenos Aires"
                    timeZone: "America/Buenos_Aires"
                Santiago de Chile:
                  value:
                    code: "SCL"
                    name: "Santiago de Chile"
                    timeZone: "America/Santiago"
      responses:
        200:
          description: city resource with the modifications.
          content:
            application/json:
              schema:
                 $ref: '#/components/schemas/CityDTO'
              examples:
                Buenos Aires:
                  value:
                    code: "BUE"
                    name: "Buenos Aires"
                    timeZone: "America/Buenos_Aires"
                Santiago de Chile:
                  value:
                    code: "SCL"
                    name: "Santiago de Chile"
                    timeZone: "America/Santiago"
        404:
          description: city not exist                   
    delete:
      summary: Delete a city resource.
      description: Remove an existing city resource having the specified id.
      parameters:
      - examples:
          Buenos Aires:
            value: "BUE"
          Santiago de Chile:
            value: "SCL"        
        name: code
        description: code name
        schema:
          type: string
        in: path
        required: true
      responses:
        204:
          description: Resource city with specified id has been removed.
          content:
            application/json:
              examples:
                Buenos Aires:
                  value: {}
                Santiago de Chile:
                  value: {}
        404:
          description: city not exist   
    parameters:
      - name: code
        in: path
        description: Code of resource
        required: true
        schema:
          type: string
components:
  schemas:
    CityDTO:
      type: object
      properties:
        name:
          type: string
        code:
          type: string
        timeZone:
          type: string
